name: My Anilist Activity
on:
  # 毎日深夜と、リポジトリにpushがあった時に実行
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
      - master

# このpermissionsブロックを追加または確認します
permissions:
  contents: write
  
jobs:
  anilist:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # 生成されるファイル名（任意の名前に変更できます）
          filename: anilist-activity.svg
          token: NOT_NEEDED
          base: "" # プロフィールカードのヘッダーや背景を非表示にします
          
          # Anilistプラグインを有効化
          plugin_anilist: yes
          
          # ★★★★★ あなたのAnilistユーザー名に変更してください ★★★★★
          plugin_anilist_user: minoD
          
          # 表示するメディアの種類 (アニメ)
          # "favorites"と"watching"セクションに適用されます
          plugin_anilist_medias: anime
          
          # 表示したいセクションをカンマ区切りで指定
          # watching: 視聴中, favorites: お気に入り, characters: 好きなキャラクター
          plugin_anilist_sections: watching, favorites, characters
          
          # 表示するアニメの最大数（お気に入り・視聴中それぞれ）
          # 必要に応じて数を変更してください
          plugin_anilist_limit: 7
          
          # 表示するキャラクターの最大数
          # 必要に応じて数を変更してください
          plugin_anilist_limit_characters: 5
